version: "1"

services:
  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod
  logs-1:
    image: logservice:latest
    ports:
      - "5000:5000"
    container_name: logs-1
  logs-2:
    image: logservice:latest
    ports:
      - "5001:5000"
    container_name: logs-2
  logs-3:
    image: logservice:latest
    ports:
      - "5002:5000"
    container_name: logs-3
  round:
    image: roundrobin:latest
    ports:
      - "47000:47000"
    container_name: round
  

volumes:
  mongodb:
  mongodb_config:
